#! /bin/sh
#
# afs	Start/Stop the OpenAFS client
# 
# chkconfig: 345 60 20
# description:  OpenAFS is a distributed filesystem.

. /etc/rc.d/init.d/functions

set -x
sortmodules() {
   echo removing lustre modules
   lctl network unconfigure 
   rmmod lustre
   rmmod lov
   rmmod osc mgc 
   sleep 1 
   rmmod mdc
   sleep 1
   #lustre2 only
   rmmod fid fld

   sleep 1
   rmmod mdc
   sleep 1
   rmmod lquota
   sleep 1
   rmmod ptlrpc
   sleep 1
   rmmod ksocklnd obdclass
   lctl network unconfigure
   rmmod lnet || ( echo failed failed to remove modules && return 1 )

}


do_umount() { 
fs=$1
mount | grep /lustre/$fs || return 0
mount | grep " /data/$fs"  
if [ $? -eq 0 ] ; then
   umount /data/$fs && umount /lustre/$fs && return 0 
   lsof | grep /data/$fs | awk '{print $2}' | xargs kill
   lsof | grep /data/$fs | awk '{print $2}' | xargs kill
   sleep 1
   lsof | grep /data/$fs | awk '{print $2}' | xargs kill
   sleep 1
   lsof | grep /data/$fs | awk '{print $2}' |  xargs kill -9
   sleep 2
   mount | grep ^/data/$fs && umount /data/$fs 
   mount | grep /data/$fs && echo failed on $fs  && return 1 
   
fi
mount | grep  /lustre/$fs && umount /lustre/$fs || ( echo failed on $fs && return 1 ) 
}


umountlustre() {

fs=atlas
while ! do_umount $fs ; do sleep 5;done
fs=lhcb
while ! do_umount $fs ; do sleep 5;done
sortmodules
sortmodules
sortmodules
sortmodules

    
}

start() {
    if [ ! -f /var/lock/subsys/lustre-shutdown ]; then
	echo "Starting lustre shudown..... "
	# Start AFS client
	touch /var/lock/subsys/lustre-shutdown
    fi
}


stop() {
    if [ -f /var/lock/subsys/lustre-shutdown ]; then

	echo "removing lustre gubbins..... "
        umountlustre
	/bin/rm -f /var/lock/subsys/lustre-shutdown
    fi
}

case "$1" in 
    start)
	start
	;;

    stop)
	stop
	;;

    restart)
	# Restart AFS
	stop
	start
	;;
  *)
	echo Usage: 'afs <start|stop|status|restart|condrestart|purgecache>'
	exit 1
esac

exit 0

action fool the Red Hat initscripts

